### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by Burner-Fuel** [DoughnutServers/DonutCraftATL#62]
When launching through the ATLauncher LAN server cannot be connected to through Tunngle VLAN on any range or through hamachi with users and pcs that work correctly in 10s of other modpacks. The server download through ATlauncher also fails on launch stating:
OS is 64
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:44)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Press any key to continue . . .
Is there any way to get the mod to work with people on VLANs not just LAN
Also your discord link has expired

**Comment by DoughnutDev** [comment]
I think this is a Minecraft crash because I am not sure if bass minecraft is able to pass a connection on a vlan because each person connecting needs to be on that same vlan for it to work and Minecraft might not like that. I can not really help any further than this.
